export * from './Header/Header'
export * from './Portfolio/Portfolio'
export * from './Contacts/Contacts'
export * from './Home/Home'
export * from './Switcher/Switcher'
export * from './Project/Project'
export * from './Projects/Projects'
export * from './PortfolioData/DataBase'